name: HALsAddon
version: ${project.versi}
author: HAL989
description: Content galore with this new addon
website: https://github.com/Gavin296/slimefun-addon-test

main: me.hal989.halsaddon.HALsAddon
depend: [Slimefun]

api-version: 1.14